# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  famtreecofoundrywebapp:
    image: famtreecofoundrywebapp
    build:
      context: .
      dockerfile: FamTree.Cofoundry.WebApp/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Jacksparrow@88"
        ACCEPT_EULA: "Y"
        volumes: 
          - mssql-server-linux-data:/var/opt/mssql/data
volumes:
  ssql-server-linux-data:
